config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/projects/:project_id/gestao_mp', :to => 'redmine_gestao_mp_home#index', as: :redmine_gestao_mp_home
get '/projects/:project_id/gestao_mp/issues', :to => 'redmine_gestao_mp_issues#index', as: :redmine_gestao_mp_issues

resources :projects do
	resources :redmine_gestao_mp_config, path: 'gestao_mp/configs'
	# resources :redmine_gestao_mp_risks, path: 'gestao_mp/risks'	do
	#	resources :redmine_gestao_mp_risk_issues, path: 'gestao_mp/issues'	
	# end
	
	resources :redmine_gestao_mp_risk_strategies, path: 'gestao_mp/risk_strategies'
	resources :issues do
		resources :redmine_gestao_mp_risk_setups, path: 'gestao_mp/risk_setup'
	end
end

app/models/redmine_gestao_mp_config.rb
class RedmineGestaoMpConfig < ActiveRecord::Base
  unloadable

  validates :name, :display_name, :scope, :value, :project_id, presence: true
  validates :name, uniqueness: {scope: [:project_id, :scope]}
  validates :display_name, uniqueness: {scope: [:project_id, :scope, :name]}

  belongs_to :project
end

app/controllers/redmine_gestao_mp_config_controller.rb
class RedmineGestaoMpConfigController < ApplicationController
  unloadable
  include ApplicationHelper
  menu_item :redmine_gestao_mp
  before_filter :find_project, :authorize
  before_filter :set_redmine_gestao_mp_config, only: [:show, :edit, :update, :destroy]

  def index
    @redmine_gestao_mp_configs = RedmineGestaoMpConfig.where(project_id: @project.id)
    @config_scopes = RedmineGestaoMpConfig.all.uniq{|c| c.scope}.map{|s| s.scope.pluralize.underscore}
  end

  def show
  end

  def new
  end

  def create
    if params[:load_config].present?  
      load_redmine_gestao_mp_config

      flash[:notice] = t('redmine_gestao_mp_youre_ready_to_start')
      respond_to do |format|
        format.html {redirect_to :back}
      end
    elsif params[:reset].present?
      @project.redmine_gestao_mp_configs.destroy_all
      load_redmine_gestao_mp_config

      flash[:notice] = t('redmine_gestao_mp_message_project_configs_successfully_reseted')
      respond_to do |format|
        format.html {redirect_to :back}
      end      
    end
  end


  def edit    
  end


  def update
    respond_to do |format|
      if @redmine_gestao_mp_config.update_attributes(params[:redmine_gestao_mp_config])
        flash[:notice] = t('redmine_gestao_mp_config_successfully_updated')
        format.html {redirect_to project_redmine_gestao_mp_config_index_path(@project, tab: params[:tab])}
      else
        flash[:notice] = t('redmine_gestao_mp_config_unsuccessfully_updated')      
        format.html { render :edit }
      end
    end
  end


  def destroy
  end


  private

  def set_redmine_gestao_mp_config
    @redmine_gestao_mp_config = RedmineGestaoMpConfig.find(params[:id])
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find_by_identifier(params[:project_id])
  end
end

app/helpers/redmine_gestao_mp_config_helper.rb
module RedmineGestaoMpConfigHelper
end

app/views/redmine_gestao_mp_config/_config_table.html.erb
<table class="list redmine-gestao-mp-configs">
  <thead>
    <tr>
      <th><%= t('redmine_gestao_mp_label_config_display_name') %></th>
      <th><%= t('redmine_gestao_mp_label_config_value') %></th>
      <th><%= t('redmine_gestao_mp_label_config_description') %></th>
      <th><%= t('redmine_gestao_mp_label_actions') %></th>
    </tr>
  </thead>
  <tbody>
  	<% redmine_gestao_mp_configs.select{|config| config.scope == scope.camelcase.singularize}.each do |config| %>
  		<tr>
  			<td><%= config.display_name %></td>
  			<td> <%= config.value %> </td>
  			<td class="redmine-gestao-mp-align-left">
          <span class="redmine-gestao-mp-config-desc-trim">
            <%= config.description %>  
          </span>          
        </td>
        <td>
          <%= link_to '', edit_project_redmine_gestao_mp_config_path(@project, config, tab: params[:tab]), class: 'icon icon-edit', alt: t('redmine_gestao_mp_label_edit'), title: t('redmine_gestao_mp_label_edit') %>
        </td>
  		</tr>
  	<% end %>
  </tbody>
</table>

app/views/redmine_gestao_mp_config/_form.html.erb
<%= labelled_form_for [@project, @redmine_gestao_mp_config] do |f| %>
	<%= hidden_field_tag :tab, params[:tab] %>
	<div class="box tabular settings">
		<p><%= f.text_field :display_name, required: true, size: 60 %></p>
		<p><%= f.text_field :value, required: true, size: 60 %></p>
		<p><%= f.text_area :description, :rows => 8, :class => 'wiki-edit' %></p>
	</div>
	<%= submit_tag l(:button_save) %>
<% end %>

app/views/redmine_gestao_mp_config/_issues.html.erb
<table class="list redmine-gestao-mp-configs">
  <thead>
    <tr>
      <th><%= t('redmine_gestao_mp_label_config_display_name') %></th>
      <th><%= t('redmine_gestao_mp_label_config_value') %></th>
      <th><%= t('redmine_gestao_mp_label_config_description') %></th>
      <th><%= t('redmine_gestao_mp_label_actions') %></th>
    </tr>
  </thead>
  <tbody>
  	<% @redmine_gestao_mp_configs.select{|config| config.scope == 'Issue'}.each do |config| %>
  		<tr>
  			<td><%= config.display_name %></td>
  			<td> <%= config.value %> </td>
  			<td class="redmine-gestao-mp-align-left">
          <span class="redmine-gestao-mp-config-desc-trim">
            <%= config.description %>  
          </span>          
        </td>
        <td>
          <%= link_to '', edit_project_redmine_gestao_mp_config_path(@project, config, tab: params[:tab]), class: 'icon icon-edit', alt: t('redmine_gestao_mp_label_edit'), title: t('redmine_gestao_mp_label_edit') %>
        </td>
  		</tr>
  	<% end %>
  </tbody>
</table>

app/views/redmine_gestao_mp_config/_lights.html.erb
<table class="list redmine-gestao-mp-configs">
  <thead>
   <tr>
      <th colspan="4">
        <%= l(:redmine_gestao_mp_label_config_issues) %>
      </th>
    </tr>
    <tr>
      <th><%= t('redmine_gestao_mp_label_config_display_name') %></th>
      <th><%= t('redmine_gestao_mp_label_config_value') %></th>
      <th><%= t('redmine_gestao_mp_label_config_description') %></th>
      <th><%= t('redmine_gestao_mp_label_actions') %></th>
    </tr>
  </thead>
  <tbody>
  	<% @redmine_gestao_mp_configs.select{|config| config.scope == 'Issue'}.each do |config| %>
  		<tr>
  			<td><%= config.display_name %></td>
  			<td> <%= config.value %> </td>
  			<td class="redmine-gestao-mp-align-left">
          <span class="redmine-gestao-mp-config-desc-trim">
            <%= config.description %>  
          </span>          
        </td>
        <td>
          <%= link_to '', edit_project_redmine_gestao_mp_config_path(@project, config, tab: params[:tab]), class: 'icon icon-edit', alt: t('redmine_gestao_mp_label_edit'), title: t('redmine_gestao_mp_label_edit') %>
        </td>
  		</tr>
  	<% end %>
  </tbody>
</table>

app/views/redmine_gestao_mp_config/_no_redmine_gestao_mp_config_found.html.erb
<% if can?(:create, :redmine_gestao_mp_config) %>
  <p>
  	<%= link_to t('redmine_gestao_mp_load_redmine_gestao_mp_configs'), project_redmine_gestao_mp_config_index_path(@project.identifier, load_config: true), method: :post %> <%= t('redmine_gestao_mp_to_start') %>.
  </p>	
<% end %>

app/views/redmine_gestao_mp_config/_projects.html.erb
<table class="list redmine-gestao-mp-configs">
  <thead>
    <tr>
      <th><%= t('redmine_gestao_mp_label_config_display_name') %></th>
      <th><%= t('redmine_gestao_mp_label_config_value') %></th>
      <th><%= t('redmine_gestao_mp_label_config_description') %></th>
      <th><%= t('redmine_gestao_mp_label_actions') %></th>
    </tr>
  </thead>
  <tbody>
  	<% @redmine_gestao_mp_configs.select{|config| config.scope == 'Project'}.each do |config| %>
  		<tr>
  			<td><%= config.display_name %></td>
  			<td> <%= config.value %> </td>
  			<td class="redmine-gestao-mp-align-left">
          <span class="redmine-gestao-mp-config-desc-trim">
            <%= config.description %>  
          </span>          
        </td>
        <td>
          <%= link_to '', edit_project_redmine_gestao_mp_config_path(@project, config, tab: params[:tab]), class: 'icon icon-edit', alt: t('redmine_gestao_mp_label_edit'), title: t('redmine_gestao_mp_label_edit') %>
        </td>
  		</tr>
  	<% end %>
  </tbody>
</table>

app/views/redmine_gestao_mp_config/edit.html.erb
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<% content_for :sidebar do %>
    <%= render :partial => 'redmine_gestao_mp_sidebar/content' %>
<% end %>

<h2><%=l(:redmine_gestao_mp_label_config_edit)%></h2>

<%= render 'form' %>

app/views/redmine_gestao_mp_config/index.html.erb
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<% content_for :sidebar do %>
    <%= render :partial => 'redmine_gestao_mp_sidebar/content' %>
<% end %>

<% if can?(:create, :redmine_gestao_mp_config) %>
  <div class="contextual">
    <%= link_to t(:redmine_gestao_mp_button_reset_project_configs), 
      project_redmine_gestao_mp_config_index_path(@project, reset: true), 
      method: :post, 
      :data => {:confirm => l(:text_are_you_sure)},
      class: 'icon icon-warning' %>
  </div>
<% end %>

<h2><%=l(:redmine_gestao_mp_label_config_plural)%></h2>



<div class="tabs">
  <ul>
    <% @config_scopes.each do |scope| %>
      <li>
        <%= link_to l("redmine_gestao_mp_label_#{scope}"), { :tab => scope }, :id => "tab-#{scope}", :class => (scope != params[:tab] ? nil : 'selected'), :onclick => "showTab('#{scope}', this.href); this.blur(); return false;" %>   
      </li>

    <% end %>
  </ul>
  
  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" type="button" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" type="button" onclick="moveTabRight(this);"></button>
  </div>
</div>

<script>
  $(document).ready(displayTabsButtons);
  $(window).resize(displayTabsButtons);
</script>

<% @config_scopes.each do |scope| %>
  <div class="tab-content" id="tab-content-<%=scope%>" style="<%= scope != params[:tab] ? 'display:none' : nil %>">
    <%= render partial: 'config_table', locals: {scope: scope, redmine_gestao_mp_configs: @redmine_gestao_mp_configs} %>
  </div>
<% end %>

app/views/redmine_gestao_mp_config/new.html.erb
<h2>RedmineGestaoMpConfigController#new</h2>

app/views/redmine_gestao_mp_config/show.html.erb
<h2>RedmineGestaoMpConfigController#show</h2>