config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/projects/:project_id/gestao_mp', :to => 'redmine_gestao_mp_home#index', as: :redmine_gestao_mp_home
get '/projects/:project_id/gestao_mp/issues', :to => 'redmine_gestao_mp_issues#index', as: :redmine_gestao_mp_issues

resources :projects do
	resources :redmine_gestao_mp_config, path: 'gestao_mp/configs'
	# resources :redmine_gestao_mp_risks, path: 'gestao_mp/risks'	do
	#	resources :redmine_gestao_mp_risk_issues, path: 'gestao_mp/issues'	
	# end
	
	resources :redmine_gestao_mp_risk_strategies, path: 'gestao_mp/risk_strategies'
	resources :issues do
		resources :redmine_gestao_mp_risk_setups, path: 'gestao_mp/risk_setup'
	end
end

app/models/redmine_gestao_mp_risk_setup.rb
class RedmineGestaoMpRiskSetup < ActiveRecord::Base
  unloadable
  belongs_to :redmine_gestao_mp_risk
  belongs_to :issue

  validates :redmine_gestao_mp_risk_id, :issue_id, presence: true
end

app/controllers/redmine_gestao_mp_risk_setups_controller.rb
class RedmineGestaoMpRiskSetupsController < ApplicationController
  unloadable
  menu_item :redmine_gestao_mp
  before_filter :find_project, :find_issue, :authorize
  before_filter :set_redmine_gestao_mp_risk_setup, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new    
    @redmine_gestao_mp_risk_setup = RedmineGestaoMpRiskSetup.new
    @project_parent_risks = @project.self_and_parent_risks.reject{|r| @issue.redmine_gestao_mp_risks.include?(r)}
    
    respond_to do |format|
      format.js
    end
  end

  def create
    @redmine_gestao_mp_risk_setup = RedmineGestaoMpRiskSetup.new(params[:redmine_gestao_mp_risk_setup])
    @redmine_gestao_mp_risk_setup.issue_id = params[:issue_id]
    @redmine_gestao_mp_risk_setup.save
    
    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @redmine_gestao_mp_risk_setup.destroy

    respond_to do |format|
      format.js
    end
  end

  private

  def set_redmine_gestao_mp_risk_setup
    @redmine_gestao_mp_risk_setup = RedmineGestaoMpRiskSetup.find(params[:id])
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find_by_identifier(params[:project_id])
  end

  def find_issue
    # @project variable must be set before calling the authorize filter
    @issue = Issue.find(params[:issue_id])
  end
end

app/helpers/redmine_gestao_mp_risk_setup_helper.rb
module RedmineGestaoMpRiskSetupHelper
end

app/views/redmine_gestao_mp_risk_setups/_form.html.erb
<%= labelled_form_for [@project, @issue, @redmine_gestao_mp_risk_setup], remote: true do |f| %>
	

		<% unless @project_parent_risks.any? %>
			<div class="flash warning" id="flash_warning">
				<%= l(:redmine_gestao_mp_risk_title_no_risk_found) %>
			</div>
		<% else %>
			<h4><%= l(:redmine_gestao_mp_risk_title_select_the_risk) %>:</h4>
			<div class="box tabular settings">
					<p >
						<%= f.grouped_collection_select :redmine_gestao_mp_risk_id, @project.self_and_parents.select{|p| p.redmine_gestao_mp_risks.any?}, :redmine_gestao_mp_risks, :identifier, :id, :type_and_title, {required: true, include_blank: t('redmine_gestao_mp_select_prompt')} %>
						<%#= f.select :redmine_gestao_mp_risk_id, options_from_collection_for_select(@project_parent_risks, :id, :project_type_and_title, f.object.redmine_gestao_mp_risk_id), {required: true, include_blank: t('redmine_gestao_mp_select_prompt')} %>
					</p>
			</div>
			<div id="redmine-gestao-mp-risk-form-details"></div>

			<%= submit_tag l(:button_save), id: "redmine-gestao-mp-risk-setup-submit-button", disabled: true %>
			<%= link_to l('button_cancel'), 'javascript:function()', onclick: 'hideModal(this);' %>
		<% end %>



<% end %>

app/views/redmine_gestao_mp_risk_setups/_risk_setup.html.erb
<% if @issue.redmine_gestao_mp_risks.any? %>
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<span data-id="<%= @project.identifier %>" id='redmine-gestap-mp-project'></span>
<hr>
<p>
	<strong><%= l(:redmine_gestao_mp_label_risk_management) %>	</strong>
</p>

<% if @issue.redmine_gestao_mp_risks.any? %>
	<%= render partial: 'redmine_gestao_mp_risk_setups/risks_table', locals: {risks: @issue.redmine_gestao_mp_risks, actions: false} %>
<% end %>
<% end %>

app/views/redmine_gestao_mp_risk_setups/_risks_table.html.erb
<% if risks.any? %>  
  <table class="list redmine-gestao-mp-risks-table">
    <thead>
      <tr>
        <th></th>
        <th><%= t('field_title') %></th>
        <th><%= t('redmine_gestao_mp_label_critically') %></th>
        <th><%= t('field_redmine_gestao_mp_risk_strategy') %></th>
        <th><%= t('field_subproject') %></th>
        <% if actions == true %>
          <th></th>          
        <% end %>
      </tr>
    </thead>
    <tbody>
    	<% risks.each do |risk| %>
        <% criticality = risk.criticality %>
    		<tr data-issues="<%= RedmineGestaoMpRiskSetup.select('issue_statuses.is_closed, issues.done_ratio').joins(:redmine_gestao_mp_risk, issue: :status).where('redmine_gestao_mp_risks.id = ?', risk.id) %>">
          <td><%= redmine_gestao_mp_risk_criticality_light(criticality) %></td>
          <td>
              <%= can?(:show, :redmine_gestao_mp_risks) ? 
                (link_to risk.title, project_redmine_gestao_mp_risk_path(@project.identifier, risk.id)) :
                risk.title
              %>
          </td>
          <td><%= criticality.display_name %></td>
          <td class='redmine-gestao-mp-risk-desc-trim'><%= risk.redmine_gestao_mp_risk_strategy.title %></td>
          <td>
            <%= redmine_gestao_mp_risk_project_display(risk, @project) %>
          </td>
          <% if actions == true %>
          <td>


            <% if can?(:destroy, :redmine_gestao_mp_risks) %>
              <%= delete_link project_issue_redmine_gestao_mp_risk_setup_path(@project.identifier, @issue.id, RedmineGestaoMpRiskSetup.find_by_redmine_gestao_mp_risk_id_and_issue_id(risk.id, @issue.id)), remote: true %>
            <% end %> 






          </td>
          <% end %>
    		</tr>
    	<% end %>
    </tbody>
  </table>
<% end %>

app/views/redmine_gestao_mp_risk_setups/create.js.erb
hideModal();
$('#redmine-gestao-mp-risk-setup-index-table').html("<%=j render partial: 'redmine_gestao_mp_risk_setups/risks_table', locals: {risks: @issue.redmine_gestao_mp_risks, actions: true} %>")

app/views/redmine_gestao_mp_risk_setups/destroy.js.erb
$('#redmine-gestao-mp-risk-setup-index-table').html("<%=j render partial: 'redmine_gestao_mp_risk_setups/risks_table', locals: {risks: @issue.redmine_gestao_mp_risks, actions: true} %>")

app/views/redmine_gestao_mp_risk_setups/edit.html.erb
<h2>RedmineGestaoMpRiskSetupController#edit</h2>

app/views/redmine_gestao_mp_risk_setups/index.html.erb
<h2>RedmineGestaoMpRiskSetupController#index</h2>

app/views/redmine_gestao_mp_risk_setups/new.html.erb
<h2>RedmineGestaoMpRiskSetupController#new</h2>

app/views/redmine_gestao_mp_risk_setups/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'redmine_gestao_mp_risk_setups/form') %>');
showModal('ajax-modal', '600px');


		$('#redmine_gestao_mp_risk_setup_redmine_gestao_mp_risk_id').on('change', function() {
			if ($(this).val() != '') {
				$('#redmine-gestao-mp-risk-setup-submit-button').removeAttr('disabled');
				$.ajax({
				  url: "/projects/<%=@project.identifier%>/gestao_mp/risks/" + $(this).val(),
				  data: {
				  	redmine_gestao_mp_risk_form_details: true
				  },
				  type: "GET",
				  dataType: "html",
				  success: function (result) {
				  	$('#redmine-gestao-mp-risk-form-details').html(result);
				  },
				  error: function (xhr, status) {
				      alert("Sorry, there was a problem!");
				  },
				  complete: function (xhr, status) {
				      //$('#showresults').slideDown('slow')
				  }
				});

			} else {
				$('#redmine-gestao-mp-risk-form-details').html('');
				$('#redmine-gestao-mp-risk-setup-submit-button').attr('disabled', 'disabled');
			}






		})

app/views/redmine_gestao_mp_risk_setups/show.html.erb
<h2>RedmineGestaoMpRiskSetupController#show</h2>