config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/projects/:project_id/gestao_mp', :to => 'redmine_gestao_mp_home#index', as: :redmine_gestao_mp_home
get '/projects/:project_id/gestao_mp/issues', :to => 'redmine_gestao_mp_issues#index', as: :redmine_gestao_mp_issues

resources :projects do
	resources :redmine_gestao_mp_config, path: 'gestao_mp/configs'
	# resources :redmine_gestao_mp_risks, path: 'gestao_mp/risks'	do
	#	resources :redmine_gestao_mp_risk_issues, path: 'gestao_mp/issues'	
	# end
	
	resources :redmine_gestao_mp_risk_strategies, path: 'gestao_mp/risk_strategies'
	resources :issues do
		resources :redmine_gestao_mp_risk_setups, path: 'gestao_mp/risk_setup'
	end
end

app/views/redmine_gestao_mp_sidebar/_content.html.erb
<h3><%= l(:redmine_gestao_mp_menu) %></h3>
<div id="admin-menu">
	<ul>
		<li><%= active_link_to l(:redmine_gestao_mp_label_home), redmine_gestao_mp_home_path(@project), class: 'redmine-gestao-mp-home-icon', active: [['redmine_gestao_mp_home'], []], wrap_tag: :li %></li>
		
		<!-- Menu de tarefas: exibe somente se possuir permissao -->
		<% if can?(:index, :redmine_gestao_mp_issues) %>
			<li><%= active_link_to l(:redmine_gestao_mp_project_light), redmine_gestao_mp_issues_path(@project), class: 'redmine-gestao-mp-traffic-light-icon', active: [['redmine_gestao_mp_issues'], []], wrap_tag: :li %></li>	
		<% end %>	

		<!-- Menu de riscos: exibe somente se possuir permissao -->
		<% if can?(:create, :redmine_gestao_mp_risks) %>
			<li><%= active_link_to l(:redmine_gestao_mp_label_risk_plural), project_redmine_gestao_mp_risks_path(@project), class: 'icon-warning', active: [['redmine_gestao_mp_risks'], []], wrap_tag: :li %></li>	
		<% end %>	

		<!-- Menu de configuração: exibe somente se possuir permissao -->
		<% if can?(:create, :redmine_gestao_mp_config) %>
			<li><%= active_link_to l(:redmine_gestao_mp_config_plural), project_redmine_gestao_mp_config_index_path(@project, tab: 'issues'), class: 'settings', active: [['redmine_gestao_mp_config'], []], wrap_tag: :li %></li>	
		<% end %>	
	</ul>
</div>