config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/projects/:project_id/gestao_mp', :to => 'redmine_gestao_mp_home#index', as: :redmine_gestao_mp_home
get '/projects/:project_id/gestao_mp/issues', :to => 'redmine_gestao_mp_issues#index', as: :redmine_gestao_mp_issues

resources :projects do
	resources :redmine_gestao_mp_config, path: 'gestao_mp/configs'
	# resources :redmine_gestao_mp_risks, path: 'gestao_mp/risks'	do
	#	resources :redmine_gestao_mp_risk_issues, path: 'gestao_mp/issues'	
	# end
	
	resources :redmine_gestao_mp_risk_strategies, path: 'gestao_mp/risk_strategies'
	resources :issues do
		resources :redmine_gestao_mp_risk_setups, path: 'gestao_mp/risk_setup'
	end
end

app/models/redmine_gestao_mp_risk.rb
class RedmineGestaoMpRisk < ActiveRecord::Base
  unloadable

  validates :title, 
  	:redmine_gestao_mp_risk_type_id, 
  	:redmine_gestao_mp_risk_probability_id, 
  	:redmine_gestao_mp_risk_impact_id, 
  	:redmine_gestao_mp_risk_strategy_id,
  	:project_id,
  presence: true

  validates :title, uniqueness: {scope: :project_id}

  belongs_to :redmine_gestao_mp_risk_type
  belongs_to :project
  belongs_to :redmine_gestao_mp_risk_strategy
  belongs_to :redmine_gestao_mp_risk_probability
  belongs_to :redmine_gestao_mp_risk_impact

  has_many :redmine_gestao_mp_risk_setups
  has_many :issues, through: :redmine_gestao_mp_risk_setups

  #  1 a  4 - Baixa
  #  5 a  9 - Média
  # 10 a 25 - Alta
  def criticality
    low_criticality_risk = RedmineGestaoMpConfig.find_by_name_and_scope_and_project_id(:low_criticality_risk, 'RedmineGestaoMpRisk', self.project.id)
    medium_criticality_risk = RedmineGestaoMpConfig.find_by_name_and_scope_and_project_id(:medium_criticality_risk, 'RedmineGestaoMpRisk', self.project.id)
    high_criticality_risk = RedmineGestaoMpConfig.find_by_name_and_scope_and_project_id(:high_criticality_risk, 'RedmineGestaoMpRisk', self.project.id)

    low_begin_rate = low_criticality_risk.value.split('-')[0].to_i
    medium_begin_rate = medium_criticality_risk.value.split('-')[0].to_i
    high_begin_rate = high_criticality_risk.value.split('-')[0].to_i

    val = self.redmine_gestao_mp_risk_probability.multiplier * self.redmine_gestao_mp_risk_impact.multiplier   
    return low_criticality_risk if val < medium_begin_rate
    return medium_criticality_risk if val > low_begin_rate and val < high_begin_rate
    return high_criticality_risk
  end

  def type_and_title
    "#{self.redmine_gestao_mp_risk_type.title} - #{self.title}"
  end

  def project_name
    self.project.identifier.upcase
  end
end

app/models/redmine_gestao_mp_risk_type.rb
class RedmineGestaoMpRiskType < ActiveRecord::Base
  unloadable
  validates :code, uniqueness: {scope: :title}
  validates :code, :title, presence: true
end

app/controllers/redmine_gestao_mp_risks_controller.rb
class RedmineGestaoMpRisksController < ApplicationController
  unloadable
  menu_item :redmine_gestao_mp
  before_filter :find_project, :authorize
  before_filter :set_redmine_gestao_mp_risk, only: [:show, :edit, :update, :destroy]

  def index
    @redmine_gestao_mp_risks = RedmineGestaoMpRisk.where(project_id: @project.parent_and_children.map{|p| p.id})
    @risks_by_type = @redmine_gestao_mp_risks.group_by{|r| r.redmine_gestao_mp_risk_type}     

    @high_start = RedmineGestaoMpConfig.where(project_id: @project.id, name: 'high_meter_risk')[0]
    @medium_start = RedmineGestaoMpConfig.where(project_id: @project.id, name: 'medium_meter_risk')[0]
    @low_start = RedmineGestaoMpConfig.where(project_id: @project.id, name: 'low_meter_risk')[0]  

  end

  def show
    if params[:redmine_gestao_mp_risk_form_details].present?
      render partial: 'risk_show_table', locals: {risk: @redmine_gestao_mp_risk}
    end
  end

  def new
    @redmine_gestao_mp_risk = RedmineGestaoMpRisk.new
  end

  def create
    @redmine_gestao_mp_risk = RedmineGestaoMpRisk.new(params[:redmine_gestao_mp_risk])
    @redmine_gestao_mp_risk.project_id = @project.id

    respond_to do |format|
      if @redmine_gestao_mp_risk.save
        format.html { redirect_to project_redmine_gestao_mp_risk_path(@project, @redmine_gestao_mp_risk) }
        format.api  { render :action => 'show', :status => :created, :location => project_redmine_gestao_mp_risk_path(@project, @redmine_gestao_mp_risk) }
      else
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@risk) }
      end
    end     

  end


  def edit    
  end


  def update
    respond_to do |format|
      if @redmine_gestao_mp_risk.update_attributes(params[:redmine_gestao_mp_risk])
        format.html { redirect_to project_redmine_gestao_mp_risk_path(@project, @redmine_gestao_mp_risk) }
        format.api  { render :action => 'show', :status => :created, :location => project_redmine_gestao_mp_risk_path(@project, @redmine_gestao_mp_risk) }
      else
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@risk) }
      end
    end     
  end


  def destroy
  end


  private

  def set_redmine_gestao_mp_risk
    @redmine_gestao_mp_risk = RedmineGestaoMpRisk.find(params[:id])
  end

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find_by_identifier(params[:project_id])
  end
end

app/helpers/redmine_gestao_mp_risks_helper.rb
module RedmineGestaoMpRisksHelper

end

app/views/redmine_gestao_mp_risks/_form.html.erb
<%= labelled_form_for [@project, @redmine_gestao_mp_risk] do |f| %>
	<%= error_messages_for 'redmine_gestao_mp_risk' %>
	<div class="box tabular settings">

		<p>
			<%= f.select :redmine_gestao_mp_risk_type_id, options_from_collection_for_select(RedmineGestaoMpRiskType.all, :id, :title, f.object.redmine_gestao_mp_risk_type_id), {required: true, include_blank: t('redmine_gestao_mp_select_prompt')} %>
		</p>

		<p><%= f.text_field :title, required: true, size: 60 %></p>
		<p><%= f.text_area :description, :rows => 8, :class => 'wiki-edit' %></p>

		<p >
			<%= f.select :redmine_gestao_mp_risk_probability_id, options_from_collection_for_select(RedmineGestaoMpRiskProbability.all, :id, :display_title, f.object.redmine_gestao_mp_risk_probability_id), {required: true, include_blank: t('redmine_gestao_mp_select_prompt')} %>
		</p>

		<p >
			<%= f.select :redmine_gestao_mp_risk_impact_id, options_from_collection_for_select(RedmineGestaoMpRiskImpact.all, :id, :display_title, f.object.redmine_gestao_mp_risk_impact_id), {required: true, include_blank: t('redmine_gestao_mp_select_prompt')} %>
		</p>

		<p >
			<%= f.select :redmine_gestao_mp_risk_strategy_id, options_from_collection_for_select(RedmineGestaoMpRiskStrategy.where(id: 0), :id, :title, f.object.redmine_gestao_mp_risk_strategy_id), {required: true, include_blank: t('redmine_gestao_mp_risks_select_risk_type_prompt')}, {"data-selected": f.object.redmine_gestao_mp_risk_strategy.try(:id)} %>
		</p>


	</div>

	<%= submit_tag l(:button_save) %>
	<%= link_to l('button_cancel'), project_redmine_gestao_mp_risks_path(@project) %>
<% end %>

app/views/redmine_gestao_mp_risks/_issues_table.html.erb
<% unless issues.any? %>
	<td colspan="3">
		<%= l(:redmine_gestao_mp_risk_title_no_issue_for_this_risk) %>		
	</td>
	</tr>		
<% else %>
  	<% issues.each_with_index do |issue, index| %>
	  	<% if index == 0 %>
				<td colspan="3"><%= link_to "#{issue.id} #{issue.subject}", issue_path(issue), target: '_blank' %></td>
				</tr>
			<% else %>
				<tr>
		  		<th></th>
					<td colspan="3"><%= link_to "#{issue.id} #{issue.subject}", issue_path(issue), target: '_blank' %></td>
				</tr>
	  	<% end %>
  	<% end %>
<% end %>

app/views/redmine_gestao_mp_risks/_risk_index_table.html.erb
<div style="width: 100%; overflow: hidden;">
  <div style="width: 10%; float: left;">
    <span id="<%=risk_type.code.downcase%>GaugeContainer" data-risk-meter="<%=risk_type.code == 'RISCONEG' ? @project.negative_risk_meter_value : 20 %>"></span>
  </div>

  <div style="margin-left: 12%">
      <table class="list redmine-gestao-mp-risks-table">
    <thead>
      <tr>
        <th></th>
        <th><%= t('field_title') %></th>
        <th><%= t('redmine_gestao_mp_label_critically') %></th>
        <th><%= t('field_redmine_gestao_mp_risk_strategy') %></th>
        <th><%= t('field_subproject') %></th>
        <th><%= t('redmine_gestao_mp_label_related_issues') %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% risks.each do |risk| %>
        <% criticality = risk.criticality %>
        <tr data-issues="<%= RedmineGestaoMpRiskSetup.select('issue_statuses.is_closed, issues.done_ratio').joins(:redmine_gestao_mp_risk, issue: :status).where('redmine_gestao_mp_risks.id = ?', risk.id) %>">
          <td><%= redmine_gestao_mp_risk_criticality_light(criticality) %></td>
          <td><%= risk.title %></td>
          <td><%= criticality.display_name %></td>
          <td class='redmine-gestao-mp-risk-desc-trim'><%= risk.redmine_gestao_mp_risk_strategy.title %></td>
          <td>
            <%= redmine_gestao_mp_risk_project_display(risk, @project) %>
          </td>
          <td>
            <%= link_to "#{risk.issues.count} #{t(:redmine_gestao_mp_label_check_related_issues)}", project_redmine_gestao_mp_risk_redmine_gestao_mp_risk_issues_path(@project.identifier, risk.id), class: 'icon icon-issue', remote: true %>

          </td>
          <td>

            <% if can?(:show, :redmine_gestao_mp_risks) %>
              <%= link_to l(:label_details), project_redmine_gestao_mp_risk_path(@project.identifier, risk.id), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-search', :accesskey => accesskey(:show) %>
            <% end %> 



            <% if can?(:edit, :redmine_gestao_mp_risks) %>
              <%= link_to l(:button_edit), edit_project_redmine_gestao_mp_risk_path(@project.identifier, risk.id), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
            <% end %> 

            
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>

</div>

app/views/redmine_gestao_mp_risks/_risk_setup.html.erb
		</div>
	</fieldset>
</div>

<%= render partial: 'redmine_gestao_mp_assets/import' %>

<fieldset class="redmine-gestao-mp-risk-setup-fieldset">
	<span data-id="<%= @project.identifier %>" id='redmine-gestap-mp-project'></span>
	<legend><%= l(:redmine_gestao_mp_label_risk_management) %></legend>


	<div id="redmine-gestao-mp-risk-setup-index-table">
		<% if @issue.redmine_gestao_mp_risks.any? %>
			<%= render partial: 'redmine_gestao_mp_risk_setups/risks_table', locals: {risks: @issue.redmine_gestao_mp_risks, actions: true} %>
		<% end %>
	</div>

	<% unless @project.self_and_parent_risks.any? %>
		<div class="flash warning" id="flash_warning">
			<%= l(:redmine_gestao_mp_risk_title_no_risk_found) %>
			<%= link_to l(:redmine_gestao_mp_go_to_risk), project_redmine_gestao_mp_risks_path(@project) %>
		</div>
	<% else %>
		<%= link_to l(:redmine_gestao_mp_add_risk_setup), new_project_issue_redmine_gestao_mp_risk_setup_path(@project.identifier, @issue.id), remote: true %>
	<% end %>
</fieldset>

app/views/redmine_gestao_mp_risks/_risk_show_table.html.erb
<div class="issue details">	
	<table class="attributes">
		<tbody>
			<tr>
				<th><%= t('field_redmine_gestao_mp_risk_type') %></th>
				<td><%= risk.redmine_gestao_mp_risk_type.title %></td>
				<th><%= t('field_title') %></th>
				<td><%= risk.title %></td>
			</tr>
			<tr>
				<th><%= t('field_redmine_gestao_mp_risk_probability') %></th>
				<td><%= risk.redmine_gestao_mp_risk_probability.title %></td>
				<th><%= t('field_redmine_gestao_mp_risk_impact') %></th>
				<td><%= risk.redmine_gestao_mp_risk_impact.title %></td>
			</tr>
			<tr>
				<th><%= t('field_redmine_gestao_mp_risk_strategy') %></th>
				<td><%= risk.redmine_gestao_mp_risk_strategy.title %></td>
				<th><%= t('redmine_gestao_mp_label_critically') %></th>
				<td>
					<% criticality = risk.criticality %>
					<%= redmine_gestao_mp_risk_criticality_light(criticality) %>					<%= criticality.display_name %>

				</td>
			</tr>
			<tr>
				<% issues = @redmine_gestao_mp_risk.issues %>
				<th><%= t('field_issue').pluralize %></th>
				<%= render partial: 'issues_table', locals: {issues: @redmine_gestao_mp_risk.issues} %>					
		</tbody>
	</table>



	<div class="description">
		<p><strong><%= t('field_description') %></strong></p>
		<div class="wiki">
			<%= risk.description %>
		</div>
	</div>


</div>

app/views/redmine_gestao_mp_risks/edit.html.erb
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<% content_for :sidebar do %>
    <%= render :partial => 'redmine_gestao_mp_sidebar/content' %>
<% end %>

<h2><%=l(:redmine_gestao_mp_label_risk_create)%></h2>
<%= render 'form' %>

app/views/redmine_gestao_mp_risks/index.html.erb
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<% content_for :sidebar do %>
    <%= render :partial => 'redmine_gestao_mp_sidebar/content' %>
<% end %>

<% if can?(:create, :redmine_gestao_mp_risks) %>
	<div class="contextual">
		<%= link_to t('redmine_gestao_mp_label_risk_create'), new_project_redmine_gestao_mp_risk_path(@project), class: 'icon redmine-gestao-mp-create-risk-icon' %>
	</div>
<% end %>

<h2><%=l(:redmine_gestao_mp_label_risk_plural)%></h2>

<% unless @redmine_gestao_mp_risks.any? %>
	<p class="nodata">
		<%= t('redmine_gestao_mp_risks_no_risks_found') %>
	</p>
<% else %>

	<div class="tabs">
	  <ul>
	  	<% @risks_by_type.keys.each do |risk_type| %>
		    <li>
		      <%= link_to risk_type.title.pluralize, { :tab => risk_type.code }, :id => "tab-#{risk_type.code}", :class => (risk_type.code != params[:tab] ? nil : 'selected'), :onclick => "showTab('#{risk_type.code}', this.href); this.blur(); return false;" %>   
		    </li>
	    <% end %>
	  </ul>
	  
	  <div class="tabs-buttons" style="display:none;">
	    <button class="tab-left" type="button" onclick="moveTabLeft(this);"></button>
	    <button class="tab-right" type="button" onclick="moveTabRight(this);"></button>
	  </div>
	</div>

	<script>
	  $(document).ready(function(){
	  	if($.getUrlVar("tab") == null) {
	  		showTab('<%=@risks_by_type.keys.first.code%>')
	  	}
	  });
	</script>

	<% @risks_by_type.keys.each do |risk_type| %>
		<div class="tab-content" id="tab-content-<%=risk_type.code%>" style="<%= risk_type.code != params[:tab] ? 'display:none' : nil %>">
		  <% unless @risks_by_type[risk_type].any? %>
		  	<p class="nodata">
					<%= t('redmine_gestao_mp_risks_no_risks_found') %>
				</p>
		  <% else %>
		  	<span id="redmine-gestao-mp-risk-ranges" 
			  	data-low-start="<%=@low_start.value.split('-')[0]%>" 
			  	data-low-end="<%=@low_start.value.split('-')[1]%>" 
			  	data-medium-start="<%=@medium_start.value.split('-')[0]%>"
			  	data-medium-end="<%=@medium_start.value.split('-')[1]%>"
			  	data-high-start="<%=@high_start.value.split('-')[0]%>"
			  	data-high-end="<%=@high_start.value.split('-')[1]%>">
		  		
		  	</span>
		  	<%= render partial: 'risk_index_table', locals: {risks: @risks_by_type[risk_type], risk_type: risk_type} %>
		  <% end %>
		</div>
	<% end %>
<% end %>

app/views/redmine_gestao_mp_risks/new.html.erb
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<% content_for :sidebar do %>
    <%= render :partial => 'redmine_gestao_mp_sidebar/content' %>
<% end %>

<h2><%=l(:redmine_gestao_mp_label_risk_create)%></h2>
<%= render 'form' %>

app/views/redmine_gestao_mp_risks/show.html.erb
<%= render partial: 'redmine_gestao_mp_assets/import' %>

<% content_for :sidebar do %>
    <%= render :partial => 'redmine_gestao_mp_sidebar/content' %>
<% end %>

<% if can?(:edit, :redmine_gestao_mp_risks) %>
	<div class="contextual">
		<%= link_to l(:button_edit), edit_project_redmine_gestao_mp_risk_path(@project.identifier, @redmine_gestao_mp_risk.id), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
	</div>
<% end %>

<h2><%= "#{t('redmine_gestao_mp_label_risk')} ##{@redmine_gestao_mp_risk.id}"%></h2>

<%= render partial: 'risk_show_table', locals: {risk: @redmine_gestao_mp_risk} %>

<%= link_to l('button_back'), project_redmine_gestao_mp_risks_path(@project) %>